---
- name: "Install all required dependencies"
  package:
    name:
      - git
      - python3
      - python3-setuptools
      - python3-pip
      - python3-virtualenv
    state: present

- name: "Add User"
  user:
    name: robo

- name: "Clone Repo"
  git:
    dest: /opt/filing13F_searcher
    repo: "https://github.com/secfilingsearcher/filing13F_searcher"
    version: main
    force: yes

- name: "Change owner to robo"
  file:
    owner: robo
    path: /opt/filing13F_searcher
    recurse: true

- name: "Install python setup.py"
  pip:
    name: /opt/filing13F_searcher/python
    virtualenv: ~/venv
  become: yes
  become_user: robo