name: React Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x, 16.x]

    # Steps represent a sequence of tasts that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        run: |
          npm ci --prefix /home/runner/work/filing13F_searcher/filing13F_searcher/frontend/13f-app
          npm run build --if-present --prefix /home/runner/work/filing13F_searcher/filing13F_searcher/frontend/13f-app
          npm test --prefix /home/runner/work/filing13F_searcher/filing13F_searcher/frontend/13f-app
