name: Pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/tests/test-requirements.txt
    - name: Install edgar_filing_searcher
      run: |
        cd python
        python setup.py install
    - name: Run tests
      run: |
        cd python
        python setup.py pytest
